### ISSUE TITLE
ValueError: invalid PageState Version

### ISSUE THREAD

**Issue by aman0019** [cclgroupltd/ccl-ssns#9]
Am imagining this is related to the the tool becoming outdated vis-a-vis the current chrome versions.

On some shallow analysis of the issue it seems the pickle I have in my files is at version 27; whereas the tool accepts up to version 23. Not sure how much work it is to fix this...but in any case I'm lodging this issue at least for it to be documented.

**Comment by Zettt** [comment]
@aman0019 Did you ever get this sorted? Is there a module missing or something? The instructions look like it should be working "out of the box".

**Comment by cclgroupltd** [comment]
@Zettt - the format of these files is changing with Chrome being updated; As @aman0019 suggests, the error is likely related to the script falling behind Chrome. We may revisit this at some point, but it's unfortunately not a priority at the moment. I'd be happy to take a look at patches though if someone wanted to contribute to getting this up to date.

**Comment by cclgroupltd** [comment]
Just to add some extra context - a lot of this stuff has been moved around in the Chrome source code so a lot of the notes I have are out of date now which means there is some significant work that needs to be done hunting down the relevant sections of the codebase to get the facts about how these files work now.

**Comment by Zettt** [comment]
@cclgroupltd Precisely. Was just hoping someone would have a current-working solution.

**Comment by aman0019** [comment]
@Zettt unfortunately I hadn't followed this up no; if I had, would definitely pushed it back here :)

**Comment by Zettt** [comment]
> @Zettt unfortunately I hadn't followed this up no; if I had, would definitely pushed it back here :)

Meh. Oh well.

**Comment by Zettt** [comment]
@aman0019 @cclgroupltd Ok guys, this is going to be a little convoluted! I found something that kinda sorta works. → https://github.com/JRBANCEL/Chromagnon/tree/SNSS

```
git clone https://github.com/JRBANCEL/Chromagnon.git
git pull origin SNSS
python chromagnonTab.py Current\ Tabs > ~/Desktop/currenttabs.txt
```

I hope this helps!

**Comment by AlexC-CCL** [comment]
There is also an updated version of this in our newer, more complete Chrome/Chromium library here: https://github.com/cclgroupltd/ccl_chromium_reader

The version in this repo is now deprecated.
